"""Profile update: Sex Enum -> Str

Revision ID: 32c57a4aa693
Revises: b3e22d96f413
Create Date: 2024-07-26 21:42:02.610485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32c57a4aa693'
down_revision: Union[str, None] = 'b3e22d96f413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'sex',
               existing_type=postgresql.ENUM('male', 'female', 'none', name='sexenum'),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'sex',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('male', 'female', 'none', name='sexenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
