"""viewed_profile status

Revision ID: 8e44e52ded57
Revises: d7dd09033e60
Create Date: 2024-08-01 10:34:40.377924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e44e52ded57'
down_revision: Union[str, None] = 'd7dd09033e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewed_profile', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viewed_profile', 'status')
    # ### end Alembic commands ###
